services:
  comfyui:
    image: ghcr.io/kramins/comfyui-amd:0.26.0
    ports:
      - "8888:8188"
    restart: no
    privileged: true
    volumes:
      - ~/comfyui:/data
      - ./:/data/custom_nodes/comfyui-power-prompt
      - /mnt/data/ai/comfyui/models:/data/models
      - /dev:/dev